/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Biblioteca;

import Conexion.Producto;
import com.sun.glass.events.KeyEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.net.URL;
import java.util.Scanner;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Daphne
 */
public class Pproducto extends javax.swing.JFrame {

    URL url = null;
    ImageIcon icon = null;

    Producto p = new Producto(); //instancia de producto

    /**
     * Creates new form Producto
     */
    public Pproducto() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    // agragar imagenes segundo metodo 
    String ruta = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblDesc = new javax.swing.JLabel();
        lblCate = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        lblCantidad = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        lblPrecioC = new javax.swing.JLabel();
        lblPrecioV = new javax.swing.JLabel();
        txtPrecioC = new javax.swing.JTextField();
        txtPrecioV = new javax.swing.JTextField();
        lblProveedor = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnCargar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        ComboBox = new javax.swing.JComboBox<>();
        mostrarL = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        cbxCategoria = new javax.swing.JComboBox<>();
        cbxProveedor = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel1.setText("PRODUCTO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 29, -1, -1));

        lblCodigo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblCodigo.setText("CODIGO:");
        jPanel1.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        lblNombre.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblNombre.setText("NOMBRE:");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        lblDesc.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblDesc.setText("DESCRIPCION:");
        jPanel1.add(lblDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        lblCate.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblCate.setText("CATEGORIA:");
        jPanel1.add(lblCate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoKeyPressed(evt);
            }
        });
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 98, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 242, -1));
        jPanel1.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 242, -1));

        lblCantidad.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblCantidad.setText("CANTIDAD:");
        jPanel1.add(lblCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 242, -1));

        lblPrecioC.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblPrecioC.setText("PRECIO C:");
        jPanel1.add(lblPrecioC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        lblPrecioV.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblPrecioV.setText("PRECIO V:");
        jPanel1.add(lblPrecioV, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));
        jPanel1.add(txtPrecioC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 242, -1));
        jPanel1.add(txtPrecioV, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 200, -1));

        lblProveedor.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblProveedor.setText("PROVEEDOR");
        jPanel1.add(lblProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jButton1.setText("Mostrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 470, -1, -1));

        btnBorrar.setText("BORAR");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, -1));

        btnCargar.setText("Guarda Datos");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, -1, -1));

        btnCerrar.setText("CERRAR");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, -1, -1));

        ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Buscando Alaska", "El señor de los Anillos", "Eleanor y Park", "Narnia", "Principito" }));
        ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, -1, -1));
        jPanel1.add(mostrarL, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 350, 230));

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane2.setViewportView(txtArea);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 240, 140));

        cbxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Novela", "Terror", "Romance", "Misterio" }));
        jPanel1.add(cbxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 240, -1));

        cbxProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "AlfaOmega", "Salamandra", "Oceano" }));
        jPanel1.add(cbxProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 240, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        /*        // TODO add your handling code here:
        String aux = "";
        String imagen = "";
        JFileChooser archivo = new JFileChooser();
        FileNameExtensionFilter filtro
                = new FileNameExtensionFilter("Imagen", "jpg");
        archivo.setFileFilter(filtro);
        int opcion = archivo.showOpenDialog(this);
        if (opcion == JFileChooser.APPROVE_OPTION) {
            try (Scanner sc = new Scanner(archivo.getSelectedFile())) {
                while (sc.hasNext()) {
                    imagen = sc.nextLine();
                    txtaDatos.append(imagen);
                }
                sc.close();
            } catch (FileNotFoundException e) {

            }
        }*/
 /*JFileChooser archivo = new JFileChooser();
        
        FileNameExtensionFilter filtro
                = new FileNameExtensionFilter("Archivo de texto", "txt"); // | este es para diferentes archivos 

        archivo.setFileFilter(filtro);

        int opcion = archivo.showSaveDialog(this); // abrir cuadro para guardadr 

        if (opcion == JFileChooser.APPROVE_OPTION) {
            try { // almacenar un arcgivo 
                BufferedWriter bw = new BufferedWriter(new FileWriter(archivo.getSelectedFile().getAbsolutePath()));

                bw.write(lblCodigo.getText()+txtCodigo.getText()+"\n");
                bw.write(lblNombre.getText()+txtNombre.getText()+"\n");
                bw.write(lblDesc.getText()+txtDescripcion.getText()+"\n");
                bw.write(lblCate.getText()+cbxCategoria.getSelectedItem()+"\n");
                bw.write(lblCantidad.getText()+txtCantidad.getText()+"\n");
                bw.write(lblPrecioC.getText()+txtPrecioC.getText()+"\n");
                bw.write(lblPrecioV.getText()+txtPrecioV.getText()+"\n");
                bw.write(lblProveedor.getText());
                bw.write(mostrarL.getText()+"\n");
                bw.write(archivo.getSelectedFile().getPath());
                
                
// escribe lo que ya tine directo en el archivo 
                bw.close();
            } catch (IOException e) {                                         // selecciona archivo y lo guarda en la ruta
                e.printStackTrace();
            }
        }
         */
        p.setCodigo(txtCodigo.getText());
        p.setNombre(txtNombre.getText());
        p.setDescripcion(txtDescripcion.getText());
        p.setCveCategoria(cbxCategoria.getSelectedIndex()); //selecciona la posicion que tiene las filas del combobox
        p.setCantidad(Integer.parseInt(txtCantidad.getText()));
        p.setPrecioC(Double.parseDouble(txtPrecioC.getText()));
        p.setPrecioV(Double.parseDouble(txtPrecioV.getText()));
        p.setCveProveedor(cbxProveedor.getSelectedIndex());
        int res = p.guardarProducto();
        if (res == 1) {
            JOptionPane.showMessageDialog(null, "Producto guardado", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
        if (res == 2) {
            JOptionPane.showMessageDialog(null, "Producto modificado", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnCargarActionPerformed

    private void ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxActionPerformed
        int op = ComboBox.getSelectedIndex();
        String cadena = ComboBox.getSelectedItem().toString();

        switch (op) {
            case 0:
                this.mostrarImagen(cadena, op, cadena);
            case 1:
                this.mostrarImagen("/img/alaska.jpg", op + 1, cadena);

                break;
            case 2:
                this.mostrarImagen("/img/anillos.jpg", op + 1, cadena);

                break;
            case 3:
                this.mostrarImagen("/img/eleanor.jpg", op + 1, cadena);

                break;
            // segunda manera
            case 4:
                this.mostrarImagen("/img/narnia.jpg", op + 1, cadena);

                break;
            case 5:
                this.mostrarImagen("/img/principito.jpg", op + 1, cadena);

                break;

        }        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /* JFileChooser archivo = new JFileChooser();
        
        FileNameExtensionFilter filtro = 
                new FileNameExtensionFilter("Archivo de texto", "txt"); // | este es para diferentes archivos 
        
        archivo.setFileFilter(filtro);
        
        int opcion = archivo.showSaveDialog(this); // abrir cuadro para guardadr 
        
        if(opcion == JFileChooser.APPROVE_OPTION){
            try{ // almacenar un arcgivo 
                BufferedWriter bw =  new BufferedWriter(new FileWriter(archivo.getSelectedFile().getAbsolutePath()));
            
            bw.write(txtaDatos.getText()); // escribe lo que ya tine directo en el archivo 
            bw.close();
            }catch (IOException e){                                         // selecciona archivo y lo guarda en la ruta
                e.printStackTrace();
            }
        }*/// TODO add your handling code here:
        String aux = "";
        String texto = "";

        JFileChooser archivo = new JFileChooser();
        archivo.showOpenDialog(this);

        File a = archivo.getSelectedFile();

        FileNameExtensionFilter filtro
                = new FileNameExtensionFilter("Archivo  de texto", "txt");
        archivo.setFileFilter(filtro);

        int opcion = archivo.showOpenDialog(this);

        if (opcion == JFileChooser.APPROVE_OPTION) {
            try (Scanner sc = new Scanner(archivo.getSelectedFile())) {
                while (sc.hasNext()) {
                    texto = sc.nextLine();
                    txtArea.append(texto + "\n");
                }
                sc.close();
            } catch (FileNotFoundException e) {
                e.printStackTrace();
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            // JOptionPane.showMessageDialog(null, "Precionó enter", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            if (p.buscarProducto(txtCodigo.getText()) == 1);

            txtNombre.setText(p.getNombre());
            txtDescripcion.setText(p.getDescripcion());
            cbxCategoria.setSelectedIndex(p.getCveCategoria());
            txtCantidad.setText(Integer.toString(p.getCantidad()));
            txtPrecioC.setText(Double.toString(p.getPrecioC()));
            txtPrecioV.setText(Double.toString(p.getPrecioV()));
        } else {
            JOptionPane.showMessageDialog(null, "Producto no encontrado", "Alerta", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtCodigoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pproducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pproducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pproducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pproducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pproducto().setVisible(true);
            }
        });
    }

    public void mostrarImagen(String urlImagen, int opcion, String cadena) {
        url = this.getClass().getResource(urlImagen);
        icon = new ImageIcon(url);
        mostrarL.setIcon(icon);
        mostrarL.setText(" Libro: " + cadena);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JComboBox<String> cbxCategoria;
    private javax.swing.JComboBox<String> cbxProveedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCate;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecioC;
    private javax.swing.JLabel lblPrecioV;
    private javax.swing.JLabel lblProveedor;
    private javax.swing.JLabel mostrarL;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecioC;
    private javax.swing.JTextField txtPrecioV;
    // End of variables declaration//GEN-END:variables
}
